version: "3"
services:
  server1:
    container_name: server1
    hostname: server1
    image: tl-vault:latest
#    entrypoint: /usr/bin/sleep
#    command: "9999999"    
    ports:
      - "8200:8200"
#     network_mode: "host"
    volumes:
    - ./configs/server1.hcl:/etc/vault.d/server.hcl:ro
    - ./configs/vault.hclic:/etc/vault.d/vault.hclic:ro
    - ./gpg:/opt/gpg:rw
    - ./raft/server1:/raft:rw
    - ./tls/vault1-key.pem:/tls/key.pem:ro
    - ./tls/vault1-cert.pem:/tls/cert.pem:ro
    - ./tls/vault-ca.pem:/tls/ca.pem:ro
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"