version: "3"
services:
  vault2node1:
    container_name: vault2node1
    hostname: vault2node1
    image: tl-vault:latest
    environment:
      - VAULT_CAPATH=/etc/vault.d/ca.pem
    env_file: vault2tokenenv.ignore
    volumes:
    - ./configs/vault.hclic:/etc/vault.d/vault.hclic:ro
    - ./configs/vault2node1.hcl:/etc/vault.d/server.hcl:ro
    - ./tls/vault-ca.pem:/etc/vault.d/ca.pem:ro
    - ./tls/vault4-cert.pem:/etc/vault.d/cert.pem:ro
    - ./tls/vault4-key.pem:/etc/vault.d/key.pem:ro
    - ./raft/vault4:/var/lib/vault:rw
  vault2node2:
    container_name: vault2node2
    hostname: vault2node2
    image: tl-vault:latest
    environment:
      - VAULT_CAPATH=/etc/vault.d/ca.pem
    env_file: vault2tokenenv.ignore
    volumes:
    - ./configs/vault.hclic:/etc/vault.d/vault.hclic:ro
    - ./configs/vault2node2.hcl:/etc/vault.d/server.hcl:ro
    - ./tls/vault-ca.pem:/etc/vault.d/ca.pem:ro
    - ./tls/vault5-cert.pem:/etc/vault.d/cert.pem:ro
    - ./tls/vault5-key.pem:/etc/vault.d/key.pem:ro
    - ./raft/vault5:/var/lib/vault:rw
  vault2node3:
    container_name: vault2node3
    hostname: vault2node3
    image: tl-vault:latest
    environment:
      - VAULT_CAPATH=/etc/vault.d/ca.pem
    env_file: vault2tokenenv.ignore
    volumes:
    - ./configs/vault.hclic:/etc/vault.d/vault.hclic:ro
    - ./configs/vault2node3.hcl:/etc/vault.d/server.hcl:ro
    - ./tls/vault-ca.pem:/etc/vault.d/ca.pem:ro
    - ./tls/vault6-cert.pem:/etc/vault.d/cert.pem:ro
    - ./tls/vault6-key.pem:/etc/vault.d/key.pem:ro
    - ./raft/vault6:/var/lib/vault:rw
  