---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: oss-vault
    image: oss-vault
    volumeMounts:
    - mountPath: /opt/vault:z
      name: pod1-dir
      readOnly: false
  volumes:
  - name: pod1-dir
    hostPath:
      path: ./volumes/pod1
      type: Directory
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: oss-vault
    image: oss-vault
    volumeMounts:
    - mountPath: /opt/vault
      name: pod2-dir
      readOnly: false
  volumes:
  - name: pod2-dir
    hostPath:
      path: ./volumes/pod2
      type: Directory
---
apiVersion: v1
kind: Pod
metadata:
  name: pod3
spec:
  containers:
  - name: oss-vault
    image: oss-vault
    volumeMounts:
    - mountPath: /opt/vault
      name: pod3-dir
      readOnly: false
  volumes:
  - name: pod3-dir
    hostPath:
      path: ./volumes/pod3
      type: Directory